# Meta
description: A minimal hexo theme.
keywords: 
site_desc: 若白驹过隙，忽然而已

# Navigation
navigation:
- name: Home
  slug: home
  url: /
- name: About
  slug: about
  url: /about
- name: Archives
  slug: archives
  url: /archives

# Search
search: 
  enable: false
  service: google # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# Miscellaneous
google_analytics:
favicon: /favicon.png
author_url: https://jiangtj.gitlab.io/me

# Less
less:
  compress: true

# use url, not username
social:
- slug: email
  url: mailto:jiang.taojie@foxmail.com
- slug: github
  url: https://github.com/jiangtj
